# Generated by Django 5.2.6 on 2025-11-17 18:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Razón Social de la empresa cliente', max_length=200)),
                ('identificacion', models.CharField(help_text='NIT o Cédula', max_length=50, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('persona_contacto', models.CharField(blank=True, max_length=200, verbose_name='Persona de Contacto')),
                ('cargo_contacto', models.CharField(blank=True, max_length=200, verbose_name='Cargo del Contacto')),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico del contacto', max_length=254)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono del contacto', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(help_text='Placa del vehículo', max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('capacidad', models.CharField(help_text="Ej: '3 toneladas', '20 m³'", max_length=100)),
                ('estado', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('MANTENIMIENTO', 'Mantenimiento')], default='OPERATIVO', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('numero_orden', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('direccion_servicio', models.CharField(help_text='Dirección principal del servicio o contrato', max_length=255)),
                ('descripcion', models.TextField(help_text='Descripción general del acuerdo o contrato')),
                ('valor_servicio', models.DecimalField(decimal_places=2, default=0.0, help_text='Costo total del acuerdo', max_digits=10)),
                ('estado_orden', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EN_EJECUCION', 'En Ejecución'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=20)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('ABONADO', 'Abonado')], default='PENDIENTE', max_length=20)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='gestion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='ordenes_documentos/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='gestion.ordenservicio')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora del Pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia'), ('EFECTIVO', 'Efectivo'), ('CONSIGNACION', 'Consignación'), ('OTRO', 'Otro')], default='TRANSFERENCIA', max_length=50)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales, número de referencia, etc.')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='gestion.ordenservicio')),
            ],
            options={
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='Recorrido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recorrido', models.DateField()),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_CURSO', 'En Curso'), ('COMPLETADO', 'Completado')], default='PROGRAMADO', max_length=20)),
                ('descripcion', models.CharField(blank=True, help_text='Descripción específica de este recorrido si es necesaria', max_length=255)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorridos', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorridos', to='gestion.ordenservicio')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorridos', to='gestion.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Manifiesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auxiliar1', models.CharField(blank=True, max_length=100, verbose_name='Auxiliar 1')),
                ('auxiliar2', models.CharField(blank=True, max_length=100, verbose_name='Auxiliar 2')),
                ('succ_canecas', models.BooleanField(default=False, verbose_name='Canecas')),
                ('succ_canecas_cant', models.CharField(blank=True, max_length=20, verbose_name='Ton/M³ Canecas')),
                ('succ_pozos_inspeccion', models.BooleanField(default=False, verbose_name='Pozos de inspección')),
                ('succ_pozos_inspeccion_cant', models.CharField(blank=True, max_length=20, verbose_name='Ton/M³ Pozos')),
                ('succ_pozos_septicos', models.BooleanField(default=False, verbose_name='Pozos Sépticos')),
                ('succ_pozos_septicos_cant', models.CharField(blank=True, max_length=20, verbose_name='Ton/M³ Sépticos')),
                ('succ_tanques', models.BooleanField(default=False, verbose_name='Tanques')),
                ('succ_tanques_cant', models.CharField(blank=True, max_length=20, verbose_name='Ton/M³ Tanques')),
                ('succ_trampas_grasa', models.BooleanField(default=False, verbose_name='Trampas de Grasa')),
                ('succ_trampas_grasa_cant', models.CharField(blank=True, max_length=20, verbose_name='Ton/M³ Trampas')),
                ('succ_otros', models.CharField(blank=True, max_length=100, verbose_name='Otros (Succión)')),
                ('succ_otros_cant', models.CharField(blank=True, max_length=20, verbose_name='Ton/M³ Otros')),
                ('sond_red_aguas_lluvias', models.BooleanField(default=False, verbose_name='Red de agua lluvias')),
                ('sond_red_aguas_lluvias_cant', models.CharField(blank=True, max_length=50, verbose_name='H/ML (Lluvias)')),
                ('sond_red_aguas_negras', models.BooleanField(default=False, verbose_name='Red de aguas negras')),
                ('sond_red_aguas_negras_cant', models.CharField(blank=True, max_length=50, verbose_name='H/ML (Negras)')),
                ('sond_red_acueducto', models.BooleanField(default=False, verbose_name='Red Acueducto')),
                ('sond_red_acueducto_cant', models.CharField(blank=True, max_length=50, verbose_name='H/ML (Acueducto)')),
                ('sond_correctivo', models.BooleanField(default=False, verbose_name='Sondeo Correctivo')),
                ('sond_correctivo_cant', models.CharField(blank=True, max_length=50, verbose_name='Valor (Correctivo)')),
                ('sond_preventivo', models.BooleanField(default=False, verbose_name='Sondeo Preventivo')),
                ('sond_preventivo_cant', models.CharField(blank=True, max_length=50, verbose_name='Valor (Preventivo)')),
                ('sond_diametro', models.CharField(blank=True, max_length=50, verbose_name='Diámetro')),
                ('lavado_concepto', models.CharField(blank=True, max_length=100, verbose_name='Concepto de Lavado')),
                ('lavado_cantidad', models.CharField(blank=True, max_length=50, verbose_name='Cantidad (Lavado)')),
                ('lavado_correctivo', models.CharField(blank=True, max_length=100, verbose_name='Lavado Correctivo')),
                ('lavado_preventivo', models.CharField(blank=True, max_length=100, verbose_name='Lavado Preventivo')),
                ('transporte_tipo', models.CharField(blank=True, max_length=100, verbose_name='Tipo de Transporte')),
                ('transporte_cantidad', models.CharField(blank=True, max_length=50, verbose_name='Cantidad (Transporte)')),
                ('tiempo_inicio_operativo', models.TimeField(blank=True, null=True, verbose_name='H. Inicio Operativo')),
                ('tiempo_final_operativo', models.TimeField(blank=True, null=True, verbose_name='H. Final Operativo')),
                ('tiempo_llegada_disposicion', models.TimeField(blank=True, null=True, verbose_name='H. Llegada sitio Disposición')),
                ('tiempo_salida_disposicion', models.TimeField(blank=True, null=True, verbose_name='H. Salida sitio Disposición')),
                ('horometro_inicio', models.TimeField(blank=True, null=True, verbose_name='H. Inicio (Horómetro)')),
                ('horometro_final', models.TimeField(blank=True, null=True, verbose_name='H. Final (Horómetro)')),
                ('km_salida_solmed', models.IntegerField(blank=True, null=True, verbose_name='Salida SolMed (Km)')),
                ('km_llegada_empresa', models.IntegerField(blank=True, null=True, verbose_name='Llegada Empresa (Km)')),
                ('km_llegada_disposicion', models.IntegerField(blank=True, null=True, verbose_name='Llegada Sitio Disposición (Km)')),
                ('km_llegada_solmed', models.IntegerField(blank=True, null=True, verbose_name='Llegada Solmed (Km)')),
                ('eval_atencion', models.IntegerField(blank=True, choices=[(1, 'Deficiente'), (2, 'Regular'), (3, 'Bueno'), (4, 'Excelente')], null=True)),
                ('eval_amabilidad', models.IntegerField(blank=True, choices=[(1, 'Deficiente'), (2, 'Regular'), (3, 'Bueno'), (4, 'Excelente')], null=True)),
                ('eval_solucion_inquietudes', models.IntegerField(blank=True, choices=[(1, 'Deficiente'), (2, 'Regular'), (3, 'Bueno'), (4, 'Excelente')], null=True)),
                ('eval_asesoria', models.IntegerField(blank=True, choices=[(1, 'Deficiente'), (2, 'Regular'), (3, 'Bueno'), (4, 'Excelente')], null=True)),
                ('eval_puntualidad', models.IntegerField(blank=True, choices=[(1, 'Deficiente'), (2, 'Regular'), (3, 'Bueno'), (4, 'Excelente')], null=True)),
                ('eval_calidad_servicio', models.IntegerField(blank=True, choices=[(1, 'Deficiente'), (2, 'Regular'), (3, 'Bueno'), (4, 'Excelente')], null=True)),
                ('eval_oportunidad', models.IntegerField(blank=True, choices=[(1, 'Deficiente'), (2, 'Regular'), (3, 'Bueno'), (4, 'Excelente')], null=True)),
                ('eval_cumplimiento_condiciones', models.IntegerField(blank=True, choices=[(1, 'Deficiente'), (2, 'Regular'), (3, 'Bueno'), (4, 'Excelente')], null=True)),
                ('eval_solucion_problemas', models.IntegerField(blank=True, choices=[(1, 'Deficiente'), (2, 'Regular'), (3, 'Bueno'), (4, 'Excelente')], null=True)),
                ('eval_volveria_contratar', models.IntegerField(blank=True, choices=[(1, 'Deficiente'), (2, 'Regular'), (3, 'Bueno'), (4, 'Excelente')], null=True)),
                ('eval_nos_recomendaria', models.IntegerField(blank=True, choices=[(1, 'Deficiente'), (2, 'Regular'), (3, 'Bueno'), (4, 'Excelente')], null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('nombre_responsable_cliente', models.CharField(blank=True, max_length=200, verbose_name='Nombre Responsable Cliente')),
                ('firma_cliente', models.ImageField(blank=True, null=True, upload_to='firmas_manifiestos/')),
                ('nombre_responsable_empresa', models.CharField(blank=True, max_length=200, verbose_name='Nombre Responsable Solmed')),
                ('pdf_generado', models.FileField(blank=True, null=True, upload_to='manifiestos_pdf/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('recorrido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manifiesto', to='gestion.recorrido')),
            ],
        ),
    ]
