# Generated by Django 5.2.6 on 2025-09-17 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la empresa o persona cliente', max_length=200)),
                ('identificacion', models.CharField(help_text='NIT, Cédula u otro identificador único', max_length=50, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(help_text='Placa del vehículo', max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('capacidad', models.CharField(help_text="Ej: '3 toneladas', '20 m³'", max_length=100)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_SERVICIO', 'En Servicio'), ('MANTENIMIENTO', 'Mantenimiento')], default='DISPONIBLE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('numero_orden', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_servicio', models.DateField()),
                ('direccion_servicio', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('estado_orden', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('ABONADO', 'Abonado')], default='PENDIENTE', max_length=20)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='gestion.cliente')),
                ('vehiculo_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='gestion.vehiculo')),
            ],
        ),
    ]
