# Generated by Django 5.2.6 on 2025-09-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='valor_servicio',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo del servicio', max_digits=10),
        ),
    ]
