# Generated by Django 5.2.6 on 2025-09-24 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manifiesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_receptor', models.CharField(help_text='Nombre de quien recibe el servicio y firma', max_length=200)),
                ('cedula_receptor', models.CharField(max_length=20)),
                ('tipo_residuo', models.CharField(default='Residuos de construcción y demolición', max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('firma_receptor', models.ImageField(upload_to='firmas_manifiestos/')),
                ('pdf_generado', models.FileField(blank=True, null=True, upload_to='manifiestos_pdf/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manifiesto', to='gestion.ordenservicio')),
            ],
        ),
    ]
