# Generated by Django 5.2.6 on 2025-10-05 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_manifiesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cargo_contacto',
            field=models.CharField(blank=True, max_length=200, verbose_name='Cargo del Contacto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='persona_contacto',
            field=models.CharField(blank=True, max_length=200, verbose_name='Persona de Contacto'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, help_text='Correo electrónico del contacto', max_length=254),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='identificacion',
            field=models.CharField(help_text='NIT o Cédula', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(help_text='Razón Social de la empresa cliente', max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, help_text='Teléfono del contacto', max_length=20),
        ),
    ]
