# Generated by Django 5.2.6 on 2025-09-24 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_ordenservicio_valor_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='ordenes_documentos/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='gestion.ordenservicio')),
            ],
        ),
    ]
