# Generated by Django 5.2.6 on 2026-06-03 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_manifiesto_token_publico_estado_firma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del gestor / dispositor')),
                ('descripcion', models.CharField(blank=True, help_text='Tipo de planta o celda, licencia ambiental, ciudad, etc.', max_length=255)),
                ('activo', models.BooleanField(default=True, help_text='Desmárcalo para ocultarlo de los formularios sin borrar el histórico.')),
            ],
            options={
                'verbose_name': 'Dispositor final autorizado',
                'verbose_name_plural': 'Dispositores finales autorizados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EncuestaConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presento_fatiga', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, verbose_name='¿Presentó síntomas de fatiga, cansancio o microsueños durante la ruta?')),
                ('nivel_combustible', models.CharField(choices=[('1/4', '¼'), ('1/2', '½'), ('3/4', '¾'), ('FULL', 'Full')], max_length=4, verbose_name='Nivel de combustible al cierre del servicio')),
                ('tipo_residuo', models.CharField(choices=[('AGUAS_DOM_SEPT', 'Aguas domésticas/sépticas'), ('AGUAS_LLUVIAS', 'Aguas lluvias'), ('TRAMPAS_GRASA', 'Trampas de grasa'), ('AGUAS_HIDROCARBURADAS', 'Aguas hidrocarburadas (RESPEL)'), ('OTROS_RESPEL', 'Otros RESPEL'), ('ORGANICOS', 'Orgánicos'), ('ESCOMBROS', 'Escombros')], max_length=30, verbose_name='Tipo de residuo transportado')),
                ('riesgo_vial', models.CharField(choices=[('NINGUNA', 'Ninguna'), ('VIA_MAL_ESTADO', 'Vía en mal estado/huecos'), ('FALTA_ILUMINACION', 'Falta de iluminación'), ('SENALIZACION_DEFICIENTE', 'Señalización deficiente'), ('PUNTO_CRITICO', 'Punto crítico de accidentes')], default='NINGUNA', max_length=30, verbose_name='Condiciones de riesgo identificadas en la infraestructura vial')),
                ('hubo_incidente', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, verbose_name='¿Se presentó algún incidente, varada o evento vial durante el trayecto?')),
                ('tipo_incidente', models.CharField(blank=True, choices=[('FALLA_MECANICA', 'Falla mecánica (Varada)'), ('INCIDENTE_MENOR', 'Incidente menor (Roce o golpe simple)'), ('SINIESTRO_TERCEROS', 'Siniestro vial con terceros')], max_length=20, verbose_name='Tipo de evento')),
                ('descripcion_incidente', models.TextField(blank=True, verbose_name='Descripción del incidente (opcional)')),
                ('fecha_diligenciamiento', models.DateTimeField(auto_now_add=True)),
                ('dispositor_final', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encuestas', to='gestion.dispositor', verbose_name='Dispositor final / destino autorizado')),
                ('recorrido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encuesta_conductor', to='gestion.recorrido')),
            ],
            options={
                'verbose_name': 'Encuesta de cierre del conductor',
                'verbose_name_plural': 'Encuestas de cierre del conductor',
            },
        ),
    ]
