# Generated by Django 5.2.6 on 2025-10-15 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_recorrido_conductor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenservicio',
            name='vehiculo',
        ),
    ]
