# Generated by Django 5.2.6 on 2026-06-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_dispositor_encuestaconductor'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuestaconductor',
            name='pdf_generado',
            field=models.FileField(blank=True, null=True, upload_to='encuestas_conductor_pdf/'),
        ),
    ]
