# Generated by Django 5.2.6 on 2025-11-16 22:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_remove_ordenservicio_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora del Pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia'), ('EFECTIVO', 'Efectivo'), ('CONSIGNACION', 'Consignación'), ('OTRO', 'Otro')], default='TRANSFERENCIA', max_length=50)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales, número de referencia, etc.')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='gestion.ordenservicio')),
            ],
            options={
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
