# Generated by Django 5.2.6 on 2026-06-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_encuestaconductor_pdf_generado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cargo_contacto2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Cargo del Contacto 2'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cargo_contacto3',
            field=models.CharField(blank=True, max_length=200, verbose_name='Cargo del Contacto 3'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email_contacto2',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo del Contacto 2'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email_contacto3',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo del Contacto 3'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='persona_contacto2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Persona de Contacto 2'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='persona_contacto3',
            field=models.CharField(blank=True, max_length=200, verbose_name='Persona de Contacto 3'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono_contacto2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono del Contacto 2'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono_contacto3',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono del Contacto 3'),
        ),
    ]
