# Generated by Django 5.2.6 on 2026-06-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_cliente_cargo_contacto2_cliente_cargo_contacto3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='identificacion',
            field=models.CharField(help_text='NIT o Cédula (puede repetirse entre sedes del mismo cliente, ej. D1 Ibagué y D1 Manizales)', max_length=50),
        ),
    ]
