# Generated by Django 5.2.6 on 2025-11-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifiesto',
            name='lavado_correctivo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lavado Correctivo'),
        ),
        migrations.AlterField(
            model_name='manifiesto',
            name='lavado_preventivo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lavado Preventivo'),
        ),
    ]
