# Generated by Django 5.2.6 on 2025-11-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_manifiesto_lavado_correctivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifiesto',
            name='sond_correctivo_cant',
            field=models.CharField(blank=True, max_length=50, verbose_name='Valor (Correctivo)'),
        ),
        migrations.AddField(
            model_name='manifiesto',
            name='sond_preventivo_cant',
            field=models.CharField(blank=True, max_length=50, verbose_name='Valor (Preventivo)'),
        ),
        migrations.AddField(
            model_name='manifiesto',
            name='sond_red_acueducto_cant',
            field=models.CharField(blank=True, max_length=50, verbose_name='H/ML (Acueducto)'),
        ),
        migrations.AddField(
            model_name='manifiesto',
            name='sond_red_aguas_lluvias_cant',
            field=models.CharField(blank=True, max_length=50, verbose_name='H/ML (Lluvias)'),
        ),
        migrations.AddField(
            model_name='manifiesto',
            name='sond_red_aguas_negras_cant',
            field=models.CharField(blank=True, max_length=50, verbose_name='H/ML (Negras)'),
        ),
    ]
