# Generated by Django 5.2.6 on 2026-06-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_cliente_identificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_vencimiento_soat',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento SOAT'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_vencimiento_tarjeta',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento Tarjeta de Propiedad'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_vencimiento_tecnomecanica',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento Tecnomecánica'),
        ),
    ]
