# Generated by Django 5.2.6 on 2026-06-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_vehiculo_fecha_vencimiento_soat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='fecha_vencimiento_tarjeta',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='archivo_soat',
            field=models.FileField(blank=True, null=True, upload_to='vehiculos_documentos/', verbose_name='PDF SOAT'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='archivo_tarjeta',
            field=models.FileField(blank=True, null=True, upload_to='vehiculos_documentos/', verbose_name='PDF Tarjeta de Propiedad'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='archivo_tecnomecanica',
            field=models.FileField(blank=True, null=True, upload_to='vehiculos_documentos/', verbose_name='PDF Tecnomecánica'),
        ),
    ]
