# Generated by Django 5.2.6 on 2026-06-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_remove_vehiculo_fecha_vencimiento_tarjeta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(choices=[('OPERATIVO', 'Operativo'), ('MANTENIMIENTO', 'En mantenimiento'), ('STAND_BY', 'Stand by (reparación mayor)')], default='OPERATIVO', max_length=20),
        ),
    ]
