# Generated by Django 5.2.6 on 2026-06-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_alter_vehiculo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sigla',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sigla'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono_celular',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono Celular'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono_fijo',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono Fijo'),
        ),
    ]
