# Generated by Django 5.2.6 on 2026-06-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_cliente_sigla_cliente_telefono_celular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ambiental_cargo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ambiental - Cargo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ambiental_correo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Ambiental - Correo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ambiental_nombre',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ambiental - Nombre'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ambiental_telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ambiental - Teléfono'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='comercial_cargo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Comercial - Cargo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='comercial_correo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Comercial - Correo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='comercial_nombre',
            field=models.CharField(blank=True, max_length=200, verbose_name='Comercial - Nombre'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='comercial_telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Comercial - Teléfono'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contab_cargo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Contabilidad - Cargo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contab_correo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Contabilidad - Correo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contab_correo_facturacion',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo de Facturación Electrónica'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contab_domicilio_fiscal',
            field=models.CharField(blank=True, max_length=255, verbose_name='Domicilio Fiscal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contab_nombre',
            field=models.CharField(blank=True, max_length=200, verbose_name='Contabilidad - Nombre'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contab_telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Contabilidad - Teléfono'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sst_cargo',
            field=models.CharField(blank=True, max_length=200, verbose_name='SST - Cargo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sst_correo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='SST - Correo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sst_nombre',
            field=models.CharField(blank=True, max_length=200, verbose_name='SST - Nombre'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sst_telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='SST - Teléfono'),
        ),
    ]
