# Generated by Django 5.2.6 on 2026-06-25 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_cliente_ambiental_cargo_cliente_ambiental_correo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cargo_contacto2',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cargo_contacto3',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email_contacto2',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email_contacto3',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='persona_contacto2',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='persona_contacto3',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono_contacto2',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono_contacto3',
        ),
    ]
