# Generated by Django 5.2.6 on 2026-06-25 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_remove_cliente_cargo_contacto2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='doc_camara_comercio',
            field=models.FileField(blank=True, null=True, upload_to='clientes_documentos/', verbose_name='Cámara de Comercio'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='doc_cedula_rep_legal',
            field=models.FileField(blank=True, null=True, upload_to='clientes_documentos/', verbose_name='Cédula del Representante Legal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='doc_rut',
            field=models.FileField(blank=True, null=True, upload_to='clientes_documentos/', verbose_name='RUT actualizado'),
        ),
        migrations.CreateModel(
            name='DocumentoAmbientalCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='clientes_documentos/ambientales/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_ambientales', to='gestion.cliente')),
            ],
            options={
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
