# Generated by Django 6.0.2 on 2026-07-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0022_remove_cuadrilla_conductor_novedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacion',
            name='exige_curso_alturas',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, verbose_name='El ayudante debe tener curso de alturas'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='exige_curso_confinados',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, verbose_name='El ayudante debe tener curso de espacios confinados'),
        ),
    ]
