# Generated by Django 6.0.2 on 2026-07-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0023_programacion_exige_curso_alturas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacion',
            name='bascula',
            field=models.CharField(blank=True, choices=[('PESAN', 'Sí'), ('NO_PESAN', 'No'), ('PESO_CLIENTE', 'Báscula del cliente')], max_length=20, verbose_name='¿Pesan en báscula?'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='registro_fotografico',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, verbose_name='¿Requiere registro fotográfico?'),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='bascula',
            field=models.CharField(blank=True, choices=[('PESAN', 'Sí'), ('NO_PESAN', 'No'), ('PESO_CLIENTE', 'Báscula del cliente')], max_length=20, verbose_name='Báscula'),
        ),
        migrations.AlterField(
            model_name='programacion',
            name='paleada',
            field=models.CharField(blank=True, choices=[('SAVICOL', 'Palea Savicol'), ('EMPOLLACOL', 'Palea Empollacol'), ('SOLO_PALEADA', 'Solo requiere paleada'), ('NO_REQUIERE', 'No requiere paleada')], max_length=20, verbose_name='Paleada'),
        ),
    ]
