# Generated by Django 6.0.2 on 2026-07-23 14:26

from django.db import migrations, models

NUEVAS = [
    'TERMINA_CLIENTE', 'TERMINA_DISPOSICION', 'RETORNA_BODEGA',
    'INICIA_CLIENTE', 'APOYA_DISPOSICION',
]


def limpiar_novedades_antiguas(apps, schema_editor):
    """
    Las novedades anteriores (NORMAL, INICIA_BODEGA, INCAPACIDAD, DESCANSA,
    PERMISO) ya no existen: las filas que las tengan quedan sin novedad para
    que no muestren un valor fuera de la lista.
    """
    Cuadrilla = apps.get_model('gestion', 'ProgramacionCuadrilla')
    Cuadrilla.objects.exclude(ayudante_novedad__in=NUEVAS).update(ayudante_novedad='')


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0024_programacion_bascula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacioncuadrilla',
            name='ayudante_novedad',
            field=models.CharField(blank=True, choices=[('TERMINA_CLIENTE', 'Termina turno donde el cliente'), ('TERMINA_DISPOSICION', 'Termina turno en el sitio de disposición'), ('RETORNA_BODEGA', 'Retorna a bodega'), ('INICIA_CLIENTE', 'Inicia turno donde el cliente'), ('APOYA_DISPOSICION', 'Apoya disposición de:')], default='', max_length=20, verbose_name='Novedad del ayudante'),
        ),
        migrations.RunPython(limpiar_novedades_antiguas, migrations.RunPython.noop),
    ]
