# Generated by Django 6.0.2 on 2026-07-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0025_alter_programacioncuadrilla_ayudante_novedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacion',
            name='paleada',
            field=models.CharField(blank=True, choices=[('SAVICOL', 'Palea Savicol'), ('EMPOLLACOL', 'Palea Empollacol'), ('SOLO_PALEADA', 'Solo requiere paleada'), ('NO_REQUIERE', 'No requiere paleada')], max_length=20, verbose_name='¿Se requiere paleada?'),
        ),
        migrations.AlterField(
            model_name='programacion',
            name='responsable_sg',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, verbose_name='¿Se requiere SGC?'),
        ),
    ]
