# Generated by Django 6.0.2 on 2026-07-24 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0026_alter_programacion_paleada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='gestion.ordenservicio'),
        ),
        migrations.AlterField(
            model_name='programacion',
            name='orden',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programacion_origen', to='gestion.ordenservicio'),
        ),
    ]
