# Generated by Django 6.0.2 on 2026-07-25 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0027_alter_pago_orden_alter_programacion_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Sede Centro, Bodega Norte…', max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('persona_contacto', models.CharField(blank=True, max_length=200, verbose_name='Persona de contacto')),
                ('activa', models.BooleanField(default=True, help_text='Desmárcala para ocultarla de los desplegables sin borrar el histórico.')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='gestion.cliente')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='programacion',
            name='sede_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programaciones', to='gestion.sede', verbose_name='Sede del cliente'),
        ),
    ]
