# Generated by Django 6.0.2 on 2026-07-25 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0028_sede_programacion_sede_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCorreoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='clientes_documentos/correo/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_correo', to='gestion.cliente')),
            ],
            options={
                'verbose_name': 'Documento del cliente para el correo',
                'verbose_name_plural': 'Documentos del cliente para el correo',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
