# Generated by Django 6.0.2 on 2026-07-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0029_documentocorreocliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilpersona',
            name='fecha_retiro',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de retiro'),
        ),
        migrations.AddField(
            model_name='perfilpersona',
            name='retirado',
            field=models.BooleanField(default=False, verbose_name='Retirado'),
        ),
    ]
