# Generated by Django 6.0.2 on 2026-07-27 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0030_perfilpersona_fecha_retiro_perfilpersona_retirado'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacion',
            name='dispositor_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programaciones', to='gestion.dispositor', verbose_name='Proveedor de disposición final'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='requiere_disposicion_final',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, verbose_name='¿Se realizará disposición final?'),
        ),
    ]
