# Generated by Django 6.0.2 on 2026-07-28 03:07

import django.db.models.deletion
from django.db import migrations, models

# Destinos que NO son disposición final real: el contenido queda en un camión
# o en los tanques de SOLMED (carga pendiente).
INTERNOS = [
    'TRASIEGO TANQUE AUXILIAR',
    'TRASIEGO TANQUE SUBTERRANEO',
    'TRASIEGO A ------ PLACA',
    'DEJAR CARRO CARGADO',
]


def marcar_internos(apps, schema_editor):
    Dispositor = apps.get_model('gestion', 'Dispositor')
    Dispositor.objects.filter(nombre__in=INTERNOS).update(tipo='INTERNO')


def desmarcar_internos(apps, schema_editor):
    Dispositor = apps.get_model('gestion', 'Dispositor')
    Dispositor.objects.filter(nombre__in=INTERNOS).update(tipo='PROVEEDOR')


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0032_seed_dispositores'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositor',
            name='tipo',
            field=models.CharField(choices=[('PROVEEDOR', 'Proveedor externo (disposición final)'), ('INTERNO', 'Destino interno (sin disposición)')], default='PROVEEDOR', max_length=10),
        ),
        migrations.AddField(
            model_name='programacion',
            name='trasiego_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trasiegos_recibidos', to='gestion.vehiculo', verbose_name='Placa a la que se trasiega'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='cargado',
            field=models.BooleanField(default=False, verbose_name='Cargado (pendiente de disposición)'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='cargado_detalle',
            field=models.CharField(blank=True, help_text='De dónde viene la carga pendiente (orden y fecha).', max_length=255),
        ),
        migrations.RunPython(marcar_internos, desmarcar_internos),
    ]
