# Generated by Django 6.0.2 on 2026-07-28 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0033_dispositor_tipo_programacion_trasiego_vehiculo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='programacioncuadrilla',
            name='ayudante2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuadrillas_como_ayudante2', to=settings.AUTH_USER_MODEL, verbose_name='Segundo ayudante (opcional)'),
        ),
        migrations.AddField(
            model_name='programacioncuadrilla',
            name='ayudante2_novedad',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Novedades del segundo ayudante'),
        ),
        migrations.AddField(
            model_name='recorrido',
            name='ayudante2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorridos_como_ayudante2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='programacioncuadrilla',
            name='ayudante_novedad',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Novedades del ayudante'),
        ),
    ]
