# Generated by Django 6.0.2 on 2026-07-28 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0034_programacioncuadrilla_ayudante2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacioncuadrilla',
            name='apoya_disposicion_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuadrillas_apoyo_ayudante', to='gestion.vehiculo', verbose_name='Apoya disposición del vehículo'),
        ),
        migrations.AddField(
            model_name='programacioncuadrilla',
            name='ayudante2_apoya_disposicion_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuadrillas_apoyo_ayudante2', to='gestion.vehiculo', verbose_name='Apoya disposición del vehículo (2º ayudante)'),
        ),
    ]
