# Generated by Django 6.0.2 on 2026-07-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0035_programacioncuadrilla_apoya_disposicion_vehiculo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RUT', 'RUT'), ('CAMARA_COMERCIO', 'Cámara de Comercio'), ('CEDULA_REP_LEGAL', 'Cédula del representante legal'), ('CEDULA_REP_SUPLENTE', 'Cédula del representante legal suplente'), ('ESTADOS_FINANCIEROS', 'Estados financieros'), ('CERTIFICACION_BANCARIA', 'Certificación bancaria'), ('RIT', 'RIT'), ('CERT_CONTRALORIA', 'Certificado de la Contraloría'), ('CERT_PROCURADURIA', 'Certificado de la Procuraduría')], max_length=30)),
                ('archivo', models.FileField(upload_to='solmed_documentos/')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha del documento')),
                ('entidad', models.CharField(blank=True, help_text='Para certificación bancaria: banco / cuenta.', max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Documento interno de SOLMED',
                'verbose_name_plural': 'Documentos internos de SOLMED',
                'ordering': ['tipo', '-fecha_subida'],
            },
        ),
    ]
