# Generated by Django 6.0.2 on 2026-07-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0036_documentointerno'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacion',
            name='lavado_cantidad',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cantidad (Lavado)'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='lavado_concepto',
            field=models.CharField(blank=True, max_length=100, verbose_name='Concepto de Lavado'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='lavado_correctivo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lavado Correctivo'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='lavado_preventivo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lavado Preventivo'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='sond_correctivo',
            field=models.BooleanField(default=False, verbose_name='Sondeo Correctivo'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='sond_correctivo_cant',
            field=models.CharField(blank=True, max_length=50, verbose_name='Valor (Correctivo)'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='sond_diametro',
            field=models.CharField(blank=True, max_length=50, verbose_name='Diámetro'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='sond_preventivo',
            field=models.BooleanField(default=False, verbose_name='Sondeo Preventivo'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='sond_preventivo_cant',
            field=models.CharField(blank=True, max_length=50, verbose_name='Valor (Preventivo)'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='sond_red_acueducto',
            field=models.BooleanField(default=False, verbose_name='Red Acueducto'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='sond_red_acueducto_cant',
            field=models.CharField(blank=True, max_length=50, verbose_name='H/ML (Acueducto)'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='sond_red_aguas_lluvias',
            field=models.BooleanField(default=False, verbose_name='Red de agua lluvias'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='sond_red_aguas_lluvias_cant',
            field=models.CharField(blank=True, max_length=50, verbose_name='H/ML (Lluvias)'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='sond_red_aguas_negras',
            field=models.BooleanField(default=False, verbose_name='Red de aguas negras'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='sond_red_aguas_negras_cant',
            field=models.CharField(blank=True, max_length=50, verbose_name='H/ML (Negras)'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='succ_canecas',
            field=models.BooleanField(default=False, verbose_name='Canecas'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='succ_canecas_cant',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ton/M³ Canecas'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='succ_otros',
            field=models.CharField(blank=True, max_length=100, verbose_name='Otros (Succión)'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='succ_otros_cant',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ton/M³ Otros'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='succ_pozos_inspeccion',
            field=models.BooleanField(default=False, verbose_name='Pozos de inspección'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='succ_pozos_inspeccion_cant',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ton/M³ Pozos'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='succ_pozos_septicos',
            field=models.BooleanField(default=False, verbose_name='Pozos Sépticos'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='succ_pozos_septicos_cant',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ton/M³ Sépticos'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='succ_tanques',
            field=models.BooleanField(default=False, verbose_name='Tanques'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='succ_tanques_cant',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ton/M³ Tanques'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='succ_trampas_grasa',
            field=models.BooleanField(default=False, verbose_name='Trampas de Grasa'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='succ_trampas_grasa_cant',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ton/M³ Trampas'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='transporte_cantidad',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cantidad (Transporte)'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='transporte_tipo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo de Transporte'),
        ),
    ]
