# Generated by Django 6.0.2 on 2026-07-29 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0038_alter_documentointerno_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre o razón social del tercero', max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('persona_contacto', models.CharField(blank=True, max_length=200, verbose_name='Persona de contacto')),
                ('activo', models.BooleanField(default=True, help_text='Desmárcalo para ocultarlo de los desplegables sin borrar el histórico.')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terceros', to='gestion.cliente')),
            ],
            options={
                'verbose_name': 'Tercero',
                'verbose_name_plural': 'Terceros',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='programacion',
            name='tercero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programaciones', to='gestion.tercero', verbose_name='Tercero del cliente'),
        ),
    ]
