# Generated by Django 6.0.2 on 2026-07-29 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0039_tercero_programacion_tercero'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoDispositor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RUT', 'RUT'), ('CAMARA_COMERCIO', 'Cámara de Comercio'), ('CEDULA_REP_LEGAL', 'Cédula del representante legal'), ('CERTIFICACION_BANCARIA', 'Certificación bancaria'), ('DOC_AMBIENTAL', 'Documento ambiental')], max_length=30)),
                ('archivo', models.FileField(upload_to='dispositores_documentos/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('dispositor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='gestion.dispositor')),
            ],
            options={
                'verbose_name': 'Documento del proveedor (dispositor)',
                'verbose_name_plural': 'Documentos de los proveedores (dispositores)',
                'ordering': ['tipo', '-fecha_subida'],
            },
        ),
    ]
