# Generated by Django 6.0.2 on 2026-07-30 02:23

from django.db import migrations, models


def clasificar_ordenes_existentes(apps, schema_editor):
    """
    Backfill: las órdenes que vienen de una programación quedan PENDIENTE o
    CONCILIADA según si "Transporte - Cantidad" se diligenció; las creadas a
    mano (sin programación) quedan NO_APLICA (el default del campo).
    """
    Programacion = apps.get_model('gestion', 'Programacion')
    OrdenServicio = apps.get_model('gestion', 'OrdenServicio')

    con_cantidad, sin_cantidad = [], []
    for prog in Programacion.objects.exclude(orden__isnull=True).only('orden_id', 'transporte_cantidad'):
        if (prog.transporte_cantidad or '').strip():
            con_cantidad.append(prog.orden_id)
        else:
            sin_cantidad.append(prog.orden_id)
    OrdenServicio.objects.filter(pk__in=con_cantidad).update(estado_conciliacion='CONCILIADA')
    OrdenServicio.objects.filter(pk__in=sin_cantidad).update(estado_conciliacion='PENDIENTE')


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0040_documentodispositor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='estado_conciliacion',
            field=models.CharField(choices=[('NO_APLICA', 'No aplica'), ('PENDIENTE', 'Pendiente de conciliación'), ('CONCILIADA', 'Conciliada')], default='NO_APLICA', max_length=20, verbose_name='Conciliación (Transporte - Cantidad)'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='fecha_conciliacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de conciliación'),
        ),
        migrations.RunPython(clasificar_ordenes_existentes, migrations.RunPython.noop),
    ]
