# Generated by Django 6.0.2 on 2026-07-30 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0042_encuesta_cierre_pesv'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiltroAceite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ACEITE_MOTOR', 'Aceite de motor'), ('ACEITE_CAJA', 'Aceite de caja'), ('ACEITE_CORONA', 'Aceite de corona / diferencial'), ('ACEITE_HIDRAULICO', 'Aceite hidráulico'), ('FILTRO_ACEITE', 'Filtro de aceite'), ('FILTRO_AIRE', 'Filtro de aire'), ('FILTRO_COMBUSTIBLE', 'Filtro de combustible'), ('FILTRO_SEPARADOR', 'Filtro separador de agua'), ('OTRO', 'Otro (indicar en la referencia)')], max_length=30)),
                ('fecha_cambio', models.DateField(verbose_name='Fecha del cambio')),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Galones/litros de aceite aplicados o número de filtros instalados.', max_digits=8, verbose_name='Cantidad')),
                ('unidad', models.CharField(choices=[('UNIDADES', 'unidad(es)'), ('GALONES', 'galón(es)'), ('LITROS', 'litro(s)'), ('CUARTOS', 'cuarto(s)')], default='UNIDADES', max_length=10)),
                ('kilometraje', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometraje en el cambio (opcional)')),
                ('referencia', models.CharField(blank=True, help_text='Ej: Mobil Delvac 15W-40, filtro FL-820S…', max_length=150, verbose_name='Referencia / marca')),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filtros_aceites', to='gestion.vehiculo')),
            ],
            options={
                'verbose_name': 'Cambio de filtro / aceite',
                'verbose_name_plural': 'Filtros y aceites del vehículo',
                'ordering': ['-fecha_cambio', '-id'],
            },
        ),
    ]
