# Generated by Django 6.0.2 on 2026-07-30 17:26

import django.db.models.deletion
from django.db import migrations, models


def sembrar_bodega(apps, schema_editor):
    """
    Siembra el sitio "Bodega" (el único lugar que existía implícito: el campo se
    llamaba "Hora ingreso a bodega") y lo asigna a las programaciones que ya
    tenían hora de ingreso registrada.
    """
    SitioInicio = apps.get_model('gestion', 'SitioInicio')
    Programacion = apps.get_model('gestion', 'Programacion')
    bodega, _ = SitioInicio.objects.get_or_create(nombre='Bodega')
    Programacion.objects.filter(
        hora_ingreso_bodega__isnull=False, sitio_inicio__isnull=True
    ).update(sitio_inicio=bodega)


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0043_filtroaceite'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitioInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('activo', models.BooleanField(default=True, help_text='Desmárcalo para ocultarlo del desplegable sin borrar el histórico.')),
            ],
            options={
                'verbose_name': 'Sitio de inicio',
                'verbose_name_plural': 'Sitios de inicio',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='programacion',
            name='hora_ingreso_bodega',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de ingreso'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='sitio_inicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programaciones', to='gestion.sitioinicio', verbose_name='Sitio de inicio'),
        ),
        migrations.RunPython(sembrar_bodega, migrations.RunPython.noop),
    ]
