# Generated by Django 6.0.2 on 2026-07-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0044_sitioinicio_alter_programacion_hora_ingreso_bodega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacion',
            name='documentos_adicionales',
            field=models.ManyToManyField(blank=True, related_name='programaciones_adjuntas', to='gestion.documentopersonal', verbose_name='Documentos adicionales del personal para el correo'),
        ),
    ]
