# Generated by Django 6.0.2 on 2026-07-31 03:24
"""
Los adjuntos adicionales del correo pasan del M2M a DocumentoPersonal (solo
permitía documentos del personal) a una lista de tokens en JSON que admite
cualquier fuente: personal, vehículo, proveedor, SOLMED y cliente. Las
selecciones ya guardadas se convierten a tokens 'personal:<id>' antes de
eliminar la tabla intermedia.
"""
from django.db import migrations, models


def m2m_a_tokens(apps, schema_editor):
    Programacion = apps.get_model('gestion', 'Programacion')
    for prog in Programacion.objects.exclude(documentos_adicionales=None).distinct():
        tokens = [f'personal:{pk}' for pk in
                  prog.documentos_adicionales.values_list('pk', flat=True)]
        if tokens:
            prog.adjuntos_correo = tokens
            prog.save(update_fields=['adjuntos_correo'])


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0045_programacion_documentos_adicionales'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacion',
            name='adjuntos_correo',
            field=models.JSONField(blank=True, default=list, verbose_name='Documentos adicionales para el correo (tokens)'),
        ),
        migrations.RunPython(m2m_a_tokens, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='programacion',
            name='documentos_adicionales',
        ),
    ]
