# Generated by Django 6.0.2 on 2026-07-31 13:30

from django.db import migrations, models


def sembrar_desde_programaciones(apps, schema_editor):
    """
    Siembra el catálogo con los residuos que ya se escribieron a mano en el
    campo (antes "Tipo de Transporte", texto libre), para que el desplegable
    arranque con lo que la empresa ya usa. Se agrupan sin distinguir
    mayúsculas ni espacios sobrantes.
    """
    TipoResiduo = apps.get_model('gestion', 'TipoResiduo')
    Programacion = apps.get_model('gestion', 'Programacion')
    vistos = {}
    # En orden de creación: si el mismo residuo se escribió de varias formas,
    # se conserva la primera (evita quedarse con una variante en minúsculas).
    for nombre in (Programacion.objects.exclude(transporte_tipo='')
                   .order_by('pk').values_list('transporte_tipo', flat=True)):
        limpio = (nombre or '').strip()
        if limpio:
            vistos.setdefault(limpio.lower(), limpio)
    for nombre in vistos.values():
        TipoResiduo.objects.get_or_create(nombre=nombre[:100])


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0046_remove_programacion_documentos_adicionales_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoResiduo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True, help_text='Desmárcalo para ocultarlo del desplegable sin borrar el histórico.')),
            ],
            options={
                'verbose_name': 'Residuo (caracterización)',
                'verbose_name_plural': 'Residuos (caracterización)',
                'ordering': ['nombre'],
            },
        ),
        migrations.RunPython(sembrar_desde_programaciones, migrations.RunPython.noop),
    ]
