# Generated by Django 6.0.2 on 2026-08-01 15:07

import django.db.models.deletion
from django.db import migrations, models

# Básculas con las que arranca el catálogo (dictadas por el usuario).
BASCULAS_INICIALES = [
    ('PARQUE INDUSTRIAL SANTA CRUZ SAS', 'KM 0 +650 VIA LOS ARBOLES PUENTE PIEDRA'),
    ('JADESI SA', 'KM 17 VIA SOACHA SIBATE'),
    ('ROBERMAR SAS', 'Carrera 36#9-68 - Carrera 36#9 70 BARRIO PENSILVANIA'),
    ('BASCULA MULERA', 'CL 35 SUR #69 64 CARVAJAL'),
    ('BASCULA CAMACHO', 'carrera 68I 37D 91'),
    ('BASCULA ECORECICLAR', 'Avenida carrera 80 16 d 40 visión Colombia zona industrial'),
    ('BASCULA PEAJE', ''),
]


def sembrar_basculas(apps, schema_editor):
    Bascula = apps.get_model('gestion', 'Bascula')
    for nombre, direccion in BASCULAS_INICIALES:
        Bascula.objects.get_or_create(nombre=nombre, defaults={'direccion': direccion})


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0048_acceso_ayudante_y_fotos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bascula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Empresa / lugar')),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True, help_text='Desmárcalo para ocultarla del desplegable sin borrar el histórico.')),
            ],
            options={
                'verbose_name': 'Báscula',
                'verbose_name_plural': 'Básculas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='programacion',
            name='bascula_sitio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programaciones', to='gestion.bascula', verbose_name='Báscula'),
        ),
        migrations.RunPython(sembrar_basculas, migrations.RunPython.noop),
    ]
