# Generated by Django 6.0.2 on 2026-08-03 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0049_bascula_programacion_bascula_sitio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacion',
            name='adjuntos_correo',
            field=models.JSONField(blank=True, default=list, verbose_name='Documentos del correo (tokens, histórico)'),
        ),
        migrations.AlterField(
            model_name='programacion',
            name='correo_seguridad_social',
            field=models.EmailField(blank=True, help_text='Ya no se usa: los correos al cliente salen del Centro de correos.', max_length=254, verbose_name='Correo del cliente (histórico)'),
        ),
        migrations.CreateModel(
            name='EnvioCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatarios', models.CharField(help_text='Uno o varios correos separados por coma.', max_length=500, verbose_name='Destinatarios')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('mensaje', models.TextField(blank=True, verbose_name='Mensaje')),
                ('adjuntos', models.JSONField(blank=True, default=list)),
                ('adjuntos_detalle', models.JSONField(blank=True, default=list)),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('estado', models.CharField(choices=[('ENVIADO', 'Enviado'), ('FALLIDO', 'Fallido')], default='ENVIADO', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='envios_correo', to='gestion.cliente', verbose_name='Cliente')),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='envios_correo', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Envío de correo',
                'verbose_name_plural': 'Envíos de correo',
                'ordering': ['-fecha'],
            },
        ),
    ]
