# Generated by Django 6.0.2 on 2026-08-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0050_envio_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentointerno',
            name='tipo',
            field=models.CharField(choices=[('RUT', 'RUT completo'), ('RUT_PRIMERA_PAGINA', 'RUT primera página'), ('CAMARA_COMERCIO', 'Cámara de Comercio'), ('CEDULA_REP_LEGAL', 'Cédula del representante legal'), ('CEDULA_REP_SUPLENTE', 'Cédula del representante legal suplente'), ('ESTADOS_FINANCIEROS', 'Estados financieros'), ('CERTIFICACION_BANCARIA', 'Certificación bancaria'), ('RIT', 'RIT'), ('CERT_CONTRALORIA', 'Certificado de la Contraloría'), ('CERT_PROCURADURIA', 'Certificado de la Procuraduría'), ('OTRO', 'Documentación adicional')], max_length=30),
        ),
    ]
