# Generated by Django 6.0.2 on 2026-08-04 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0051_documento_interno_adicional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCargaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CARGA', 'Carga'), ('DESCARGA', 'Descarga')], max_length=10)),
                ('nota', models.CharField(help_text='De dónde viene la carga o a dónde se dispuso.', max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('dispositor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='descargas_registradas', to='gestion.dispositor', verbose_name='Proveedor de disposición')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_carga_registrados', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_carga', to='gestion.vehiculo')),
            ],
            options={
                'verbose_name': 'Movimiento de carga del vehículo',
                'verbose_name_plural': 'Movimientos de carga de los vehículos',
                'ordering': ['-fecha'],
            },
        ),
    ]
