# Generated by Django 6.0.2 on 2026-08-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0052_movimiento_carga_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviocorreo',
            name='responder_a',
            field=models.CharField(blank=True, help_text='Correo al que llegan las respuestas de quien lo recibe.', max_length=500, verbose_name='Responder a'),
        ),
    ]
