# Generated by Django 6.0.2 on 2026-08-06 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0054_dispositor_sin_disposicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedidaACPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INICIAL', 'Medida inicial'), ('TANQUEADA_1', 'Medida tanqueada 1'), ('TANQUEADA_2', 'Medida tanqueada 2')], max_length=15)),
                ('medida', models.CharField(blank=True, help_text='Lo que marca el medidor o los galones tanqueados.', max_length=50, verbose_name='Medida')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='acpm_fotos/')),
                ('manifiesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidas_acpm', to='gestion.manifiesto')),
            ],
            options={
                'verbose_name': 'Medida de ACPM',
                'verbose_name_plural': 'Control de ACPM',
                'ordering': ['tipo'],
                'unique_together': {('manifiesto', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='NovedadOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('HOROMETRO', 'Horómetro'), ('MONTALLANTAS', 'Montallantas'), ('STANDBY', 'Stand by'), ('VARADA', 'Varada'), ('TANQUEO_EXTERNO', 'Tanqueo externo'), ('CAMBIO_CONDUCTOR', 'Cambio de conductor'), ('COMPRA_REPUESTO', 'Compra de repuesto'), ('DEMORA_DISPOSITOR', 'Demora en la recepción del dispositor'), ('DEMORA_CLIENTE', 'Demora en la atención del cliente'), ('RETEN_POLICIA', 'Retén de policía'), ('INMOVILIZACION', 'Inmovilización'), ('APOYO', 'Apoyo a…')], max_length=20)),
                ('observacion', models.CharField(blank=True, max_length=255, verbose_name='Observaciones')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora inicio')),
                ('hora_final', models.TimeField(blank=True, null=True, verbose_name='Hora final')),
                ('manifiesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades_operacionales', to='gestion.manifiesto')),
            ],
            options={
                'verbose_name': 'Novedad operacional',
                'verbose_name_plural': 'Novedades operacionales',
                'ordering': ['tipo'],
                'unique_together': {('manifiesto', 'tipo')},
            },
        ),
    ]
