# Generated by Django 6.0.2 on 2026-08-08 04:58

"""
Quita el HORÓMETRO SISTEMA DE VACÍO del acta: ya no se pide en la hoja del
conductor ni sale en el PDF.

⚠️ DESTRUCTIVA: borra las columnas `horometro_inicio` y `horometro_final` de
`manifiesto` con los datos que tuvieran. Es irreversible (revertir la migración
recrea las columnas vacías).
"""
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0055_novedades_operacionales_y_acpm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifiesto',
            name='horometro_final',
        ),
        migrations.RemoveField(
            model_name='manifiesto',
            name='horometro_inicio',
        ),
    ]
