# Generated by Django 6.0.2 on 2026-08-09 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0056_quitar_horometro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuestaconductor',
            name='pdf_generado',
        ),
    ]
