# Generated by Django 6.0.2 on 2026-08-11 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0057_remove_encuestaconductor_pdf_generado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifiesto',
            name='pdf_generado',
        ),
    ]
