# Generated by Django 6.0.2 on 2026-08-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0058_remove_manifiesto_pdf_generado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifiesto',
            name='km_llegada_disposicion',
        ),
        migrations.RemoveField(
            model_name='manifiesto',
            name='km_llegada_empresa',
        ),
        migrations.RemoveField(
            model_name='manifiesto',
            name='km_llegada_solmed',
        ),
        migrations.RemoveField(
            model_name='manifiesto',
            name='km_salida_solmed',
        ),
        migrations.AddField(
            model_name='manifiesto',
            name='hora_llegada_disposicion',
            field=models.TimeField(blank=True, null=True, verbose_name='H. Llegada Sitio Disposición'),
        ),
        migrations.AddField(
            model_name='manifiesto',
            name='hora_llegada_empresa',
            field=models.TimeField(blank=True, null=True, verbose_name='H. Llegada Empresa'),
        ),
        migrations.AddField(
            model_name='manifiesto',
            name='hora_llegada_solmed',
            field=models.TimeField(blank=True, null=True, verbose_name='H. Llegada SolMed'),
        ),
        migrations.AddField(
            model_name='manifiesto',
            name='hora_salida_solmed',
            field=models.TimeField(blank=True, null=True, verbose_name='H. Salida SolMed'),
        ),
    ]
