# Generated by Django 6.0.2 on 2026-08-14 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0059_remove_manifiesto_km_llegada_disposicion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True, help_text='Desmárcalo para ocultarlo del desplegable sin borrar el histórico.')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=30, verbose_name='NIT')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=200, verbose_name='Nombre comercial')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('tipo_cuenta', models.CharField(blank=True, choices=[('AHORROS', 'Ahorros'), ('CORRIENTE', 'Corriente'), ('NEQUI', 'Nequi'), ('DAVIPLATA', 'Daviplata'), ('OTRA', 'Otra')], max_length=10, verbose_name='Tipo de cuenta')),
                ('numero_cuenta', models.CharField(blank=True, max_length=50, verbose_name='No. de cuenta')),
                ('activo', models.BooleanField(default=True, help_text='Desmárcalo para archivarlo sin borrar su expediente.')),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedores', to='gestion.banco')),
            ],
            options={
                'verbose_name': 'Proveedor general',
                'verbose_name_plural': 'Proveedores generales',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del documento')),
                ('archivo', models.FileField(upload_to='proveedores_documentos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='gestion.proveedor')),
            ],
            options={
                'verbose_name': 'Documento del proveedor general',
                'verbose_name_plural': 'Documentos de los proveedores generales',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='ContactoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=120)),
                ('area', models.CharField(blank=True, max_length=120, verbose_name='Área')),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('celular', models.CharField(blank=True, max_length=30)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='gestion.proveedor')),
            ],
            options={
                'verbose_name': 'Contacto del proveedor',
                'verbose_name_plural': 'Contactos del proveedor',
                'ordering': ['id'],
            },
        ),
    ]
