# Generated by Django 6.0.2 on 2026-08-19 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0061_sembrar_bancos'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocargavehiculo',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_carga', to='gestion.ordenservicio', verbose_name='Orden relacionada'),
        ),
    ]
