# Generated by Django 6.0.2 on 2026-08-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0062_movimiento_carga_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacioncuadrilla',
            name='conductor_solo',
            field=models.BooleanField(default=False, verbose_name='El conductor va solo (sin ayudante)'),
        ),
    ]
