# Generated by Django 6.0.2 on 2026-08-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0063_conductor_solo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentopersonal',
            name='tipo',
            field=models.CharField(choices=[('CEDULA', 'Cédula de ciudadanía'), ('SEGURIDAD_SOCIAL', 'Seguridad social (EPS/ARL/Pensión)'), ('ARL', 'Afiliación a ARL (personal nuevo)'), ('LICENCIA', 'Licencia de conducción'), ('CURSO_ALTURAS', 'Certificado curso de alturas'), ('CURSO_CONFINADOS', 'Certificado espacios confinados'), ('OTRO', 'Otro documento')], max_length=20),
        ),
    ]
