# Generated by Django 6.0.2 on 2026-08-25 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0064_documento_arl'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocargavehiculo',
            name='descarga',
            field=models.ForeignKey(blank=True, limit_choices_to={'accion': 'DESCARGA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargas_saldadas', to='gestion.movimientocargavehiculo', verbose_name='Descarga que la saldó'),
        ),
    ]
