# Generated by Django 6.0.2 on 2026-09-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0066_saldar_cargas_historicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacioncuadrilla',
            name='ayudante2_observacion',
            field=models.TextField(blank=True, help_text='Se las verá en su correo y en su enlace personal.', verbose_name='Observaciones para el segundo ayudante'),
        ),
        migrations.AddField(
            model_name='programacioncuadrilla',
            name='ayudante_observacion',
            field=models.TextField(blank=True, help_text='Se las verá en su correo y en su enlace personal.', verbose_name='Observaciones para el ayudante'),
        ),
    ]
