# Generated by Django 6.0.2 on 2026-09-14 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0067_programacioncuadrilla_ayudante2_observacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='estado_disposicion',
            field=models.CharField(choices=[('NO_APLICA', 'No aplica'), ('PENDIENTE', 'Sin disponer'), ('DISPUESTA', 'Dispuesta')], default='NO_APLICA', max_length=12, verbose_name='Disposición del residuo'),
        ),
        migrations.CreateModel(
            name='DisposicionOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Día de la disposición')),
                ('via', models.CharField(choices=[('PLAN', 'Plan de trabajo'), ('CONVERTIR', 'Al convertir la orden'), ('REPORTE', 'Reporte de la oficina'), ('MANUAL', 'Corregida a mano')], max_length=10)),
                ('nota', models.CharField(blank=True, max_length=255)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('deshecha', models.BooleanField(default=False)),
                ('deshecha_en', models.DateTimeField(blank=True, null=True)),
                ('deshecha_nota', models.CharField(blank=True, max_length=255)),
                ('deshecha_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disposiciones_deshechas', to=settings.AUTH_USER_MODEL)),
                ('dispositor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disposiciones', to='gestion.dispositor', verbose_name='Gestor de disposición')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposiciones', to='gestion.ordenservicio')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disposiciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disposición de la orden',
                'verbose_name_plural': 'Disposiciones de las órdenes',
                'ordering': ['-fecha', '-pk'],
            },
        ),
    ]
