# Generated by Django 6.0.2 on 2026-09-14 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0069_migrar_disposiciones_a_la_orden'),
        # El plan debe soltar su enlace a las descargas antes de borrar el modelo.
        ('planes', '0006_retirar_descargas_del_camion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='cargado',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='cargado_detalle',
        ),
        migrations.DeleteModel(
            name='MovimientoCargaVehiculo',
        ),
    ]
