# Generated by Django 6.0.2 on 2026-09-17 12:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0070_retirar_la_carga_del_camion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(editable=False, unique=True)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('orden_compra', models.CharField(blank=True, max_length=100, verbose_name='Orden de compra')),
                ('correo_facturacion', models.EmailField(blank=True, max_length=254, verbose_name='Correo de facturación')),
                ('numero_externo', models.CharField(blank=True, max_length=50, verbose_name='Número de la factura electrónica')),
                ('xml', models.FileField(blank=True, null=True, upload_to='facturas/xml/', verbose_name='Factura XML')),
                ('pdf_oficial', models.FileField(blank=True, null=True, upload_to='facturas/pdf/', verbose_name='Factura electrónica (PDF)')),
                ('copiar_factura', models.BooleanField(default=True, verbose_name='Factura')),
                ('copiar_xml', models.BooleanField(default=True, verbose_name='XML')),
                ('copiar_actas', models.BooleanField(default=False, verbose_name='O.T.S. (actas firmadas)')),
                ('estado', models.CharField(choices=[('EMITIDA', 'Emitida'), ('ENVIADA', 'Enviada al cliente')], default='EMITIDA', max_length=10)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='gestion.cliente')),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='AdjuntoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('archivo', models.FileField(upload_to='facturas/adjuntos/')),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='gestion.factura')),
            ],
            options={
                'ordering': ['subido_en'],
            },
        ),
        migrations.CreateModel(
            name='LineaFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='gestion.factura')),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='linea_factura', to='gestion.ordenservicio')),
            ],
            options={
                'ordering': ['orden__numero_orden'],
            },
        ),
    ]
