# Generated by Django 6.0.2 on 2026-09-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0071_facturacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineafactura',
            name='observaciones',
            field=models.CharField(blank=True, max_length=255, verbose_name='Observaciones adicionales'),
        ),
    ]
