# Generated by Django 6.0.2 on 2026-09-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0072_observaciones_por_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='observaciones_internas',
            field=models.TextField(blank=True, help_text='Solo para la oficina: no sale en el PDF ni se envía al cliente.', verbose_name='Observaciones internas'),
        ),
    ]
