# Generated by Django 6.0.2 on 2026-09-18 20:20

import django.utils.timezone
from django.db import migrations, models


def fecha_real_de_las_existentes(apps, schema_editor):
    """
    Las facturas que ya existen llevan la fecha en que se registraron, no la
    del día de la migración (que es lo que pondría el default).
    """
    Factura = apps.get_model('gestion', 'Factura')
    from django.utils import timezone
    tocadas = 0
    for factura in Factura.objects.all():
        factura.fecha_emision = timezone.localtime(factura.creada_en).date()
        factura.save(update_fields=['fecha_emision'])
        tocadas += 1
    if tocadas:
        print(f"\n  Fecha de emisión puesta a {tocadas} factura(s) ya registradas.")


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0073_observaciones_internas'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de emisión'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.RunPython(fecha_real_de_las_existentes, migrations.RunPython.noop),
    ]
