# Generated by Django 6.0.2 on 2026-09-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0074_numero_y_fecha_de_la_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='archivo_orden_compra',
            field=models.FileField(blank=True, null=True, upload_to='facturas/orden_compra/', verbose_name='Orden de compra (archivo)'),
        ),
        migrations.AddField(
            model_name='factura',
            name='archivo_orden_pedido',
            field=models.FileField(blank=True, null=True, upload_to='facturas/orden_pedido/', verbose_name='Orden de pedido (archivo)'),
        ),
        migrations.AddField(
            model_name='factura',
            name='copiar_basculas',
            field=models.BooleanField(default=False, verbose_name='Básculas'),
        ),
        migrations.AddField(
            model_name='factura',
            name='copiar_orden_compra',
            field=models.BooleanField(default=False, verbose_name='Orden de compra'),
        ),
        migrations.AddField(
            model_name='factura',
            name='copiar_orden_pedido',
            field=models.BooleanField(default=False, verbose_name='Orden de pedido'),
        ),
        migrations.AddField(
            model_name='factura',
            name='copiar_otros',
            field=models.BooleanField(default=False, verbose_name='Otros'),
        ),
        migrations.AddField(
            model_name='lineafactura',
            name='copiar_bascula',
            field=models.BooleanField(default=True, verbose_name='Enviar su tiquete de báscula'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='copiar_actas',
            field=models.BooleanField(default=False, verbose_name='Órdenes de servicio'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='copiar_factura',
            field=models.BooleanField(default=True, verbose_name='Factura electrónica de venta'),
        ),
    ]
