# Generated by Django 6.0.2 on 2026-09-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0075_adjuntos_al_cliente_en_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='correo_facturacion',
            field=models.CharField(blank=True, help_text='Uno o varios, separados por coma.', max_length=500, verbose_name='Correos de facturación'),
        ),
    ]
