# Generated by Django 6.0.2 on 2026-09-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0076_varios_correos_de_facturacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='orden_compra',
        ),
        migrations.AddField(
            model_name='factura',
            name='corte_facturacion',
            field=models.CharField(blank=True, help_text='Solo para la oficina: no se le muestra ni se le envía al cliente.', max_length=100, verbose_name='Corte de facturación'),
        ),
    ]
