# Generated by Django 6.0.2 on 2026-09-23 14:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0077_corte_de_facturacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Concepto')),
                ('precio', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
            ],
            options={
                'verbose_name': 'Concepto adicional',
                'verbose_name_plural': 'Conceptos adicionales',
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='lineafactura',
            name='lleva_global',
            field=models.BooleanField(default=True, verbose_name='Lleva el global de la orden'),
        ),
        migrations.AlterField(
            model_name='lineafactura',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_factura', to='gestion.ordenservicio'),
        ),
        migrations.AddConstraint(
            model_name='lineafactura',
            constraint=models.UniqueConstraint(fields=('factura', 'orden'), name='linea_unica_por_factura'),
        ),
        migrations.AddConstraint(
            model_name='lineafactura',
            constraint=models.UniqueConstraint(condition=models.Q(('lleva_global', True)), fields=('orden',), name='global_de_la_orden_una_sola_vez'),
        ),
        migrations.AddField(
            model_name='conceptofactura',
            name='linea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='gestion.lineafactura'),
        ),
    ]
