# Generated by Django 6.0.2 on 2026-09-23 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0078_conceptos_adicionales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fe_realizada_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Factura electrónica realizada el'),
        ),
        migrations.AddField(
            model_name='factura',
            name='fe_realizada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_electronicas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Factura electrónica realizada por'),
        ),
    ]
