# Generated by Django 6.0.2 on 2026-09-24 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0079_factura_electronica_realizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartes', to='gestion.factura', verbose_name='Preliquidación principal'),
        ),
    ]
