# Generated by Django 6.0.2 on 2026-09-24 23:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0080_pdf_aparte'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineafactura',
            name='destruccion',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Destrucción'),
        ),
        migrations.AddField(
            model_name='lineafactura',
            name='flete',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='lineafactura',
            name='peso_organicos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Peso orgánicos'),
        ),
        migrations.AddField(
            model_name='lineafactura',
            name='peso_peligrosos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Peso peligrosos'),
        ),
        migrations.AddField(
            model_name='lineafactura',
            name='unitario_organicos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Valor unitario orgánicos'),
        ),
        migrations.AddField(
            model_name='lineafactura',
            name='unitario_peligrosos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Valor unitario peligrosos'),
        ),
    ]
