# Generated by Django 6.0.2 on 2026-09-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0081_detalle_d1'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilpersona',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='personal/fotos/', verbose_name='Foto'),
        ),
    ]
