# Generated by Django 6.0.2 on 2026-09-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0082_foto_de_la_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilpersona',
            name='arl',
            field=models.CharField(blank=True, help_text='Administradora de riesgos laborales a la que está afiliada', max_length=100, verbose_name='ARL'),
        ),
        migrations.AddField(
            model_name='perfilpersona',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso'),
        ),
    ]
