# Generated by Django 6.0.2 on 2026-10-06 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0083_fecha_de_ingreso_y_arl'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoDisposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del certificado')),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('archivo', models.FileField(upload_to='disposiciones_finales/')),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificados_disposicion', to='gestion.cliente')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificado de disposición final',
                'verbose_name_plural': 'Certificados de disposición final',
                'ordering': ['-fecha', '-subido_en'],
            },
        ),
    ]
