# Generated by Django 6.0.2 on 2026-08-18 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0061_sembrar_bancos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Ausencias y salud', [('AUSENCIA', 'Ausencia'), ('CALAMIDAD', 'Calamidad doméstica'), ('EXAMEN_MEDICO', 'Examen médico (ingreso · periódico · anual)'), ('INCAPACIDAD_EPS', 'Incapacidad EPS'), ('INCAPACIDAD_ARL', 'Incapacidad ARL')]), ('Licencias', [('LIC_MATERNIDAD', 'Licencia de maternidad'), ('LIC_PATERNIDAD', 'Licencia de paternidad'), ('LIC_LUTO', 'Licencia por luto'), ('LIC_ADOPCION', 'Licencia por adopción'), ('LIC_REMUNERADA', 'Licencia remunerada'), ('LIC_NO_REMUNERADA', 'Licencia no remunerada')]), ('Permisos', [('PERMISO_ESPECIALISTA', 'Permiso: cita con especialista'), ('PERMISO_CITA_MEDICA', 'Permiso: cita médica / terapia'), ('PERMISO_PERSONAL', 'Permiso personal'), ('PERMISO_EXEQUIAL', 'Permiso exequial'), ('PERMISO_ESCOLAR', 'Permiso escolar'), ('PERMISO_VOTACION', 'Permiso para votar'), ('JURADO_VOTACION', 'Jurado de votación'), ('CITACION_JUDICIAL', 'Citación judicial')]), ('Trabajo interno', [('TRABAJO_BODEGA', 'Trabajo en bodega'), ('TRABAJO_OFICINA', 'Trabajo en oficina')]), ('Situaciones laborales', [('DESCANSO', 'Descanso'), ('COMPENSATORIO', 'Compensatorio'), ('VACACIONES', 'Vacaciones'), ('INGRESO_NUEVO', 'Ingreso de trabajador nuevo'), ('DESCARGOS', 'Citado a descargos'), ('RENUNCIA', 'Renuncia'), ('DESPIDO', 'Despido')])], max_length=25)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, help_text='Vacía = la novedad es solo del día de inicio.', null=True, verbose_name='Fecha final')),
                ('hora', models.TimeField(blank=True, help_text='Para permisos de unas horas.', null=True)),
                ('detalle', models.CharField(blank=True, max_length=255, verbose_name='Detalle')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades_plan', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='novedades_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Novedad del plan de trabajo',
                'verbose_name_plural': 'Novedades del plan de trabajo',
                'ordering': ['-fecha_inicio', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlanDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('notas', models.TextField(blank=True, help_text='Lo que el equipo deba tener presente (van al PDF).', verbose_name='Observaciones del día')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan de trabajo (día)',
                'verbose_name_plural': 'Planes de trabajo (días)',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TECNOMECANICA', 'Tecnomecánica'), ('LAVADA', 'Lavada de vehículo'), ('MANT_EXTERNO', 'Mantenimiento externo'), ('MANT_INTERNO', 'Mantenimiento interno'), ('VISITA_TECNICA', 'Visita técnica'), ('COMPRA_REPUESTOS', 'Compra de repuestos'), ('MONTALLANTAS', 'Servicio de montallantas'), ('TRASTEO', 'Trasteo'), ('DISPOSICION_FINAL', 'Disposición final'), ('DISPOSICION_SOLMED', 'Disposición de Solmed SAS'), ('ACOMPANAMIENTO', 'Acompañamiento'), ('RECOGER_VEHICULO', 'Recoger vehículo'), ('DESTRUCCION_CANECAS', 'Destrucción, separación y alistamiento de canecas'), ('APOYO_SERVICIO', 'Apoyo a servicio'), ('APOYO_DISPOSICION', 'Apoyo a disposición'), ('OTRA', 'Otra actividad')], max_length=25)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('detalle', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_plan', to='gestion.ordenservicio', verbose_name='Orden de servicio')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_plan', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_plan', to='gestion.proveedor', verbose_name='Proveedor externo')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_registradas', to=settings.AUTH_USER_MODEL)),
                ('vehiculos', models.ManyToManyField(blank=True, related_name='asignaciones_plan', to='gestion.vehiculo', verbose_name='Placa(s)')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='planes.plandia')),
            ],
            options={
                'verbose_name': 'Asignación del plan',
                'verbose_name_plural': 'Asignaciones del plan',
                'ordering': ['id'],
            },
        ),
    ]
