# Generated by Django 6.0.2 on 2026-08-19 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0062_movimiento_carga_orden'),
        ('planes', '0001_plan_de_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='dispositor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_plan', to='gestion.dispositor', verbose_name='Gestor de disposición'),
        ),
    ]
