# Generated by Django 6.0.2 on 2026-08-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0066_saldar_cargas_historicas'),
        ('planes', '0002_disposicion_descarga'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='descargas',
            field=models.ManyToManyField(blank=True, related_name='asignaciones_plan', to='gestion.movimientocargavehiculo', verbose_name='Descargas registradas'),
        ),
    ]
