# Generated by Django 6.0.2 on 2026-09-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0068_disposicion_de_la_orden'),
        ('planes', '0004_enlazar_descargas_previas'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='disposiciones',
            field=models.ManyToManyField(blank=True, related_name='asignaciones_plan', to='gestion.disposicionorden', verbose_name='Disposiciones registradas'),
        ),
    ]
