# Generated by Django 6.0.2 on 2026-09-14 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0005_disposicion_de_la_orden'),
        # Primero se migran los datos a la orden; luego se suelta el enlace viejo.
        ('gestion', '0069_migrar_disposiciones_a_la_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='descargas',
        ),
    ]
