"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar variables de entorno del archivo .env
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# Lista separada por comas en el .env. Ej: ALLOWED_HOSTS=midominio.com,www.midominio.com,127.0.0.1
# En desarrollo (DEBUG=True) se permiten localhost/127.0.0.1 por defecto si no se define nada.
ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '').split(',') if h.strip()]
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# --- CSRF detrás de HTTPS / proxy (Django >= 4) ---
# Para que los formularios POST (login, etc.) funcionen por HTTPS, Django exige
# declarar el origen completo (con esquema). Se derivan de ALLOWED_HOSTS y se
# pueden ampliar con CSRF_TRUSTED_ORIGINS en el .env (separados por comas).
CSRF_TRUSTED_ORIGINS = [
    f'https://{h}' for h in ALLOWED_HOSTS if h not in ('localhost', '127.0.0.1')
]
CSRF_TRUSTED_ORIGINS += [
    o.strip() for o in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()
]

# Detrás de Nginx/Load Balancer que termina el TLS: confiar en el proto reenviado
# para que Django sepa que la petición original llegó por HTTPS.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'gestion.apps.GestionConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Banderas de rol (es_administrador, es_asesor, ...) para el menú.
                'gestion.context_processors.roles',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True

USE_L10N = True

# Sin separador de miles automático: pintaba los números de orden como
# "#22.207" (son identificadores, no cantidades). El dinero conserva su
# separador porque las plantillas usan |intcomma explícito.
USE_THOUSAND_SEPARATOR = False

# Static & Media files — almacenamiento híbrido (local en desarrollo, AWS S3 en producción).
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Carpeta(s) de origen de los estáticos del proyecto.
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
# Destino de collectstatic (requerido para servir estáticos en producción).
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'gestion:dashboard' # A dónde ir después de loguearse
LOGOUT_REDIRECT_URL = 'login' # A dónde ir después de cerrar sesión


# Ruta en disco para archivos subidos en desarrollo.
MEDIA_ROOT = BASE_DIR / 'media'

# --- Almacenamiento híbrido: LOCAL (DEBUG=True) vs AWS S3 (DEBUG=False) ---
if DEBUG:
    # MODO DESARROLLO (LOCAL)
    STATIC_URL = '/static/'
    MEDIA_URL = '/media/'
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }
else:
    # MODO PRODUCCIÓN (AWS S3). Credenciales vía IAM Role del EC2 (sin access keys).
    from storages.backends.s3boto3 import S3Boto3Storage

    AWS_STORAGE_BUCKET_NAME = 'vadomdata'
    AWS_S3_REGION_NAME = 'us-east-1'

    # Los objetos son PRIVADOS (sin ACL pública). Se sirven con URLs FIRMADAS
    # temporales (presigned), que usan las credenciales del IAM Role y funcionan
    # aunque el bucket tenga bloqueado el acceso público. Esto mantiene privados
    # los documentos de seguridad social (datos personales).
    #
    # IMPORTANTE: NO se define AWS_S3_CUSTOM_DOMAIN. Al fijarlo, django-storages
    # devuelve URLs públicas directas SIN firmar -> AccessDenied en objetos
    # privados (que era el problema).
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = True          # firma las URLs (.url() presigned)
    AWS_QUERYSTRING_EXPIRE = 3600        # validez del enlace firmado: 1 hora
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_S3_FILE_OVERWRITE = False

    # Prefijo (carpeta) de este cliente dentro del bucket compartido.
    S3_PREFIX = os.getenv('S3_CLIENT_PREFIX', 'default_prefix')

    class StaticStorage(S3Boto3Storage):
        location = f'{S3_PREFIX}/static'
        default_acl = None
        custom_domain = None             # firmar también los estáticos (logo)

    class MediaStorage(S3Boto3Storage):
        location = f'{S3_PREFIX}/media'
        default_acl = None
        custom_domain = None

    # Django exige STATIC_URL/MEDIA_URL; para cada archivo se usa storage.url()
    # (firmado), así que estos valores son solo la base informativa.
    STATIC_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/{S3_PREFIX}/static/'
    MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/{S3_PREFIX}/media/'

    STORAGES = {
        "default": {"BACKEND": "config.settings.MediaStorage"},
        "staticfiles": {"BACKEND": "config.settings.StaticStorage"},
    }


# La URL a la que se redirigirá a los usuarios si intentan acceder a una página protegida sin estar logueados.
LOGIN_URL = 'login'

# La URL a la que se redirigirá a los usuarios DESPUÉS de un inicio de sesión exitoso.
LOGIN_REDIRECT_URL = 'gestion:dashboard_redirect'

# La URL a la que se redirigirá a los usuarios DESPUÉS de cerrar sesión.
LOGOUT_REDIRECT_URL = 'login'


# --- Correo saliente (SMTP) ---
# Credenciales en el .env (nunca en el repo). Puerto 465 = SSL implícito.
# Si no hay servidor configurado, se usa el backend de consola (los correos se
# imprimen en la terminal) para no romper nada en desarrollo.
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '465'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'True') == 'True'
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'False') == 'True'
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'no-reply@localhost')
EMAIL_TIMEOUT = 20

# A dónde llegan las RESPUESTAS de quien recibe el correo. El mensaje sigue
# saliendo de DEFAULT_FROM_EMAIL (la cuenta del sistema), pero al pulsar
# "Responder" el correo se dirige aquí: así las respuestas de los clientes caen
# en una bandeja atendida. Admite varias direcciones separadas por coma.
# Vacío = las respuestas van a la cuenta del sistema (comportamiento anterior).
EMAIL_REPLY_TO = [
    c.strip() for c in os.getenv('EMAIL_REPLY_TO', '').split(',') if c.strip()
]

if EMAIL_HOST:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
